spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false # 开启了用户验证
      database: bussystem

  neo4j:
    authentication:
      password: 123456
      username: neo4j
    uri: bolt://localhost:7687

server:
  port: 9090