spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false  # 开启了用户验证
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      database: bussystem

  neo4j:
    authentication:
      password: xochitlqx77
      username: neo4j
    uri: bolt://localhost:7687

server:
  port: 9090